# Generated by Django 5.1.1 on 2024-10-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_postmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
