# Generated by Django 5.1.1 on 2024-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_public_postmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='public_state',
            field=models.BooleanField(default=True),
        ),
    ]
