# Generated by Django 5.1.1 on 2024-11-02 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_rename_enterprise_professionaldata_company_and_more'),
        ('post', '0008_remove_postmodel_title_postmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='profile',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.profile'),
        ),
    ]
