# Generated by Django 5.1.1 on 2024-11-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseProfile', '0001_initial'),
        ('UserProfile', '0006_rename_enterprise_professionaldata_company_and_more'),
        ('post', '0009_postmodel_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='profile',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='EnterpriseProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnterpriseProfile.enterpriseprofile'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.profile'),
        ),
    ]
