# Generated by Django 5.1.1 on 2024-11-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnterpriseProfile', '0001_initial'),
        ('UserProfile', '0006_rename_enterprise_professionaldata_company_and_more'),
        ('post', '0010_remove_postmodel_profile_postmodel_enterpriseprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='EnterpriseProfile',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EnterpriseProfile.enterpriseprofile'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='UserProfile',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.profile'),
        ),
    ]
