# Generated by Django 5.1.1 on 2024-11-05 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('backstory', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profile_banners/')),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('foundationDate', models.CharField(max_length=60)),
                ('workers', models.PositiveIntegerField()),
                ('field', models.CharField(max_length=120)),
                ('enterprise', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_data', to='EnterpriseProfile.enterpriseprofile')),
            ],
        ),
    ]
