# Generated by Django 5.1.1 on 2024-10-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaldata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='professionaldata',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='UserProfile.educationaldata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='UserProfile.personaldata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='professional_data',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='UserProfile.professionaldata'),
            preserve_default=False,
        ),
    ]
