# Generated by Django 5.1.1 on 2024-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_state',
            field=models.BooleanField(default=True),
        ),
    ]
